"""
Data Access Object for managing trading signals.

This module provides database operations for creating, retrieving, and updating
trading signals generated by strategies.
"""

import json
import logging
from datetime import date, datetime, timedelta
from typing import Dict, List, Optional

import mysql.connector

from .base_dao import BaseDAO
from .utility import DatabaseConnectionPool

logger = logging.getLogger(__name__)


class TradingSignalDAO(BaseDAO):
    """Data Access Object for trading signals."""

    def __init__(self, pool: DatabaseConnectionPool):
        """
        Initialize the TradingSignalDAO.

        Args:
            pool: Database connection pool
        """
        super().__init__(pool)

    def save_signal(
        self,
        strategy_id: int,
        ticker_id: int,
        signal_type: str,
        signal_strength: str,
        confidence_score: float,
        indicator_snapshot: Dict,
        price_at_signal: float,
        portfolio_id: Optional[int] = None,
        signal_date: Optional[datetime] = None,
        expires_date: Optional[datetime] = None,
    ) -> Optional[int]:
        """
        Save a new trading signal.

        Args:
            strategy_id: Strategy that generated this signal
            ticker_id: Ticker this signal is for
            signal_type: BUY, SELL, or HOLD
            signal_strength: STRONG, MODERATE, or WEAK
            confidence_score: Confidence level 0-100
            indicator_snapshot: All indicator values at signal time
            price_at_signal: Stock price when signal was generated
            portfolio_id: Portfolio this signal applies to (optional)
            signal_date: When signal was generated (defaults to now)
            expires_date: When signal expires (optional)

        Returns:
            int: The ID of the created signal, or None on error
        """
        try:
            # Default to current datetime if not specified
            if signal_date is None:
                signal_date = datetime.now()

            # Convert indicator snapshot to JSON
            indicator_snapshot_json = json.dumps(indicator_snapshot)

            with self.get_connection() as connection:
                cursor = connection.cursor()
                query = """
                    INSERT INTO trading_signals
                    (strategy_id, portfolio_id, ticker_id, signal_type, signal_strength,
                     confidence_score, indicator_snapshot, price_at_signal, signal_date,
                     expires_date, status)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 'PENDING')
                """
                values = (
                    strategy_id,
                    portfolio_id,
                    ticker_id,
                    signal_type,
                    signal_strength,
                    confidence_score,
                    indicator_snapshot_json,
                    price_at_signal,
                    signal_date,
                    expires_date,
                )
                cursor.execute(query, values)
                signal_id = cursor.lastrowid
                logger.info(
                    f"Created signal {signal_id}: {signal_type} for ticker_id={ticker_id}"
                )
                return signal_id

        except mysql.connector.Error as e:
            logger.error(f"Error saving trading signal: {e}")
            return None

    def get_signal(self, signal_id: int) -> Optional[Dict]:
        """
        Retrieve a single signal by ID with full details.

        Args:
            signal_id: The signal ID

        Returns:
            Dict containing signal details, or None if not found
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor(dictionary=True)
                query = """
                    SELECT
                        sig.*,
                        strat.name as strategy_name,
                        strat.strategy_type,
                        t.ticker as ticker_symbol,
                        t.ticker_name,
                        p.name as portfolio_name
                    FROM trading_signals sig
                    INNER JOIN trading_strategies strat ON sig.strategy_id = strat.id
                    INNER JOIN tickers t ON sig.ticker_id = t.id
                    LEFT JOIN portfolio p ON sig.portfolio_id = p.id
                    WHERE sig.id = %s
                """
                cursor.execute(query, (signal_id,))
                result = cursor.fetchone()

                if result and result.get("indicator_snapshot"):
                    # Parse JSON indicator snapshot
                    result["indicator_snapshot"] = json.loads(result["indicator_snapshot"])

                return result

        except mysql.connector.Error as e:
            logger.error(f"Error retrieving signal {signal_id}: {e}")
            return None

    def get_active_signals(
        self,
        portfolio_id: Optional[int] = None,
        ticker_id: Optional[int] = None,
        strategy_id: Optional[int] = None,
    ) -> List[Dict]:
        """
        Get all active (pending) signals, optionally filtered.

        Args:
            portfolio_id: Filter by portfolio ID
            ticker_id: Filter by ticker ID
            strategy_id: Filter by strategy ID

        Returns:
            List of active signal dictionaries
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor(dictionary=True)

                query = """
                    SELECT
                        sig.*,
                        strat.name as strategy_name,
                        strat.strategy_type,
                        t.ticker as ticker_symbol,
                        t.ticker_name,
                        p.name as portfolio_name
                    FROM trading_signals sig
                    INNER JOIN trading_strategies strat ON sig.strategy_id = strat.id
                    INNER JOIN tickers t ON sig.ticker_id = t.id
                    LEFT JOIN portfolio p ON sig.portfolio_id = p.id
                    WHERE sig.status = 'PENDING'
                    AND (sig.expires_date IS NULL OR sig.expires_date > NOW())
                """
                params = []

                if portfolio_id is not None:
                    query += " AND sig.portfolio_id = %s"
                    params.append(portfolio_id)

                if ticker_id is not None:
                    query += " AND sig.ticker_id = %s"
                    params.append(ticker_id)

                if strategy_id is not None:
                    query += " AND sig.strategy_id = %s"
                    params.append(strategy_id)

                query += " ORDER BY sig.signal_date DESC, sig.confidence_score DESC"

                cursor.execute(query, tuple(params))
                results = cursor.fetchall()

                # Parse JSON for each result
                for result in results:
                    if result.get("indicator_snapshot"):
                        result["indicator_snapshot"] = json.loads(
                            result["indicator_snapshot"]
                        )

                return results

        except mysql.connector.Error as e:
            logger.error(f"Error retrieving active signals: {e}")
            return []

    def get_signal_history(
        self,
        strategy_id: Optional[int] = None,
        ticker_id: Optional[int] = None,
        portfolio_id: Optional[int] = None,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        signal_type: Optional[str] = None,
        status: Optional[str] = None,
        limit: int = 100,
        offset: int = 0,
    ) -> List[Dict]:
        """
        Get historical signals with optional filters.

        Args:
            strategy_id: Filter by strategy ID
            ticker_id: Filter by ticker ID
            portfolio_id: Filter by portfolio ID
            start_date: Filter by start date
            end_date: Filter by end date
            signal_type: Filter by signal type (BUY, SELL, HOLD)
            status: Filter by status (PENDING, ACTED_ON, etc.)
            limit: Maximum number of results
            offset: Offset for pagination

        Returns:
            List of signal dictionaries
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor(dictionary=True)

                query = """
                    SELECT
                        sig.*,
                        strat.name as strategy_name,
                        strat.strategy_type,
                        t.ticker as ticker_symbol,
                        t.ticker_name,
                        p.name as portfolio_name
                    FROM trading_signals sig
                    INNER JOIN trading_strategies strat ON sig.strategy_id = strat.id
                    INNER JOIN tickers t ON sig.ticker_id = t.id
                    LEFT JOIN portfolio p ON sig.portfolio_id = p.id
                    WHERE 1=1
                """
                params = []

                if strategy_id is not None:
                    query += " AND sig.strategy_id = %s"
                    params.append(strategy_id)

                if ticker_id is not None:
                    query += " AND sig.ticker_id = %s"
                    params.append(ticker_id)

                if portfolio_id is not None:
                    query += " AND sig.portfolio_id = %s"
                    params.append(portfolio_id)

                if start_date is not None:
                    query += " AND DATE(sig.signal_date) >= %s"
                    params.append(start_date)

                if end_date is not None:
                    query += " AND DATE(sig.signal_date) <= %s"
                    params.append(end_date)

                if signal_type is not None:
                    query += " AND sig.signal_type = %s"
                    params.append(signal_type)

                if status is not None:
                    query += " AND sig.status = %s"
                    params.append(status)

                query += " ORDER BY sig.signal_date DESC LIMIT %s OFFSET %s"
                params.extend([limit, offset])

                cursor.execute(query, tuple(params))
                results = cursor.fetchall()

                # Parse JSON for each result
                for result in results:
                    if result.get("indicator_snapshot"):
                        result["indicator_snapshot"] = json.loads(
                            result["indicator_snapshot"]
                        )

                return results

        except mysql.connector.Error as e:
            logger.error(f"Error retrieving signal history: {e}")
            return []

    def update_signal_status(
        self,
        signal_id: int,
        status: str,
        outcome: Optional[str] = None,
        profit_loss: Optional[float] = None,
        profit_loss_pct: Optional[float] = None,
    ) -> bool:
        """
        Update a signal's status and optionally its outcome/performance.

        Args:
            signal_id: The signal ID
            status: New status (PENDING, ACTED_ON, IGNORED, EXPIRED, CANCELLED)
            outcome: Optional outcome (SUCCESS, FAILURE, NEUTRAL, PENDING)
            profit_loss: Optional P/L amount
            profit_loss_pct: Optional P/L percentage

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor()

                # Build query based on what's being updated
                query = "UPDATE trading_signals SET status = %s"
                params = [status]

                if outcome is not None:
                    query += ", outcome = %s, evaluation_date = NOW()"
                    params.append(outcome)

                if profit_loss is not None:
                    query += ", profit_loss = %s"
                    params.append(profit_loss)

                if profit_loss_pct is not None:
                    query += ", profit_loss_pct = %s"
                    params.append(profit_loss_pct)

                query += " WHERE id = %s"
                params.append(signal_id)

                cursor.execute(query, tuple(params))
                rows_affected = cursor.rowcount
                logger.info(f"Updated signal {signal_id} status to {status}")
                return rows_affected > 0

        except mysql.connector.Error as e:
            logger.error(f"Error updating signal status: {e}")
            return False

    def link_signal_to_transaction(
        self, signal_id: int, transaction_id: int
    ) -> bool:
        """
        Link a signal to a portfolio transaction.

        Args:
            signal_id: The signal ID
            transaction_id: The portfolio transaction ID

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor()
                query = """
                    UPDATE trading_signals
                    SET transaction_id = %s, status = 'ACTED_ON'
                    WHERE id = %s
                """
                cursor.execute(query, (transaction_id, signal_id))
                rows_affected = cursor.rowcount
                logger.info(f"Linked signal {signal_id} to transaction {transaction_id}")
                return rows_affected > 0

        except mysql.connector.Error as e:
            logger.error(f"Error linking signal to transaction: {e}")
            return False

    def link_signal_to_recommendation(
        self, signal_id: int, recommendation_id: int
    ) -> bool:
        """
        Link a signal to an AI recommendation.

        Args:
            signal_id: The signal ID
            recommendation_id: The AI recommendation ID

        Returns:
            bool: True if successful, False otherwise
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor()
                query = """
                    UPDATE trading_signals
                    SET recommendation_id = %s
                    WHERE id = %s
                """
                cursor.execute(query, (recommendation_id, signal_id))
                rows_affected = cursor.rowcount
                logger.info(
                    f"Linked signal {signal_id} to recommendation {recommendation_id}"
                )
                return rows_affected > 0

        except mysql.connector.Error as e:
            logger.error(f"Error linking signal to recommendation: {e}")
            return False

    def expire_old_signals(
        self, strategy_id: Optional[int] = None, portfolio_id: Optional[int] = None
    ) -> int:
        """
        Mark expired signals as EXPIRED.

        Args:
            strategy_id: Optional filter by strategy
            portfolio_id: Optional filter by portfolio

        Returns:
            int: Number of signals expired
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor()

                query = """
                    UPDATE trading_signals
                    SET status = 'EXPIRED', updated_at = NOW()
                    WHERE status = 'PENDING'
                    AND expires_date IS NOT NULL
                    AND expires_date < NOW()
                """
                params = []

                if strategy_id is not None:
                    query += " AND strategy_id = %s"
                    params.append(strategy_id)

                if portfolio_id is not None:
                    query += " AND portfolio_id = %s"
                    params.append(portfolio_id)

                cursor.execute(query, tuple(params))
                expired_count = cursor.rowcount

                if expired_count > 0:
                    logger.info(f"Expired {expired_count} old signals")

                return expired_count

        except mysql.connector.Error as e:
            logger.error(f"Error expiring old signals: {e}")
            return 0

    def get_signal_summary(
        self, portfolio_id: Optional[int] = None, strategy_id: Optional[int] = None
    ) -> Dict:
        """
        Get summary statistics for signals.

        Args:
            portfolio_id: Optional filter by portfolio
            strategy_id: Optional filter by strategy

        Returns:
            Dict containing signal counts and statistics
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor(dictionary=True)

                query = """
                    SELECT
                        COUNT(*) as total_signals,
                        COUNT(CASE WHEN signal_type = 'BUY' THEN 1 END) as buy_signals,
                        COUNT(CASE WHEN signal_type = 'SELL' THEN 1 END) as sell_signals,
                        COUNT(CASE WHEN status = 'PENDING' THEN 1 END) as pending_signals,
                        COUNT(CASE WHEN status = 'ACTED_ON' THEN 1 END) as acted_on_signals,
                        COUNT(CASE WHEN outcome = 'SUCCESS' THEN 1 END) as successful_signals,
                        COUNT(CASE WHEN outcome = 'FAILURE' THEN 1 END) as failed_signals,
                        AVG(confidence_score) as avg_confidence,
                        SUM(profit_loss) as total_profit_loss,
                        AVG(profit_loss) as avg_profit_loss
                    FROM trading_signals
                    WHERE 1=1
                """
                params = []

                if portfolio_id is not None:
                    query += " AND portfolio_id = %s"
                    params.append(portfolio_id)

                if strategy_id is not None:
                    query += " AND strategy_id = %s"
                    params.append(strategy_id)

                cursor.execute(query, tuple(params))
                result = cursor.fetchone()

                # Calculate win rate if applicable
                if result and result["acted_on_signals"] > 0:
                    result["win_rate"] = (
                        result["successful_signals"] / result["acted_on_signals"]
                    ) * 100
                else:
                    result["win_rate"] = None

                return result if result else {}

        except mysql.connector.Error as e:
            logger.error(f"Error retrieving signal summary: {e}")
            return {}

    def check_duplicate_signal(
        self,
        strategy_id: int,
        ticker_id: int,
        signal_date: datetime,
        time_window_hours: int = 24,
    ) -> bool:
        """
        Check if a similar signal already exists within a time window.

        Args:
            strategy_id: Strategy ID
            ticker_id: Ticker ID
            signal_date: Signal date/time
            time_window_hours: Time window in hours to check for duplicates

        Returns:
            bool: True if duplicate exists, False otherwise
        """
        try:
            with self.get_connection() as connection:
                cursor = connection.cursor()

                # Calculate time window
                start_time = signal_date - timedelta(hours=time_window_hours)
                end_time = signal_date + timedelta(hours=time_window_hours)

                query = """
                    SELECT COUNT(*) as count
                    FROM trading_signals
                    WHERE strategy_id = %s
                    AND ticker_id = %s
                    AND signal_date BETWEEN %s AND %s
                    AND status = 'PENDING'
                """
                cursor.execute(query, (strategy_id, ticker_id, start_time, end_time))
                result = cursor.fetchone()

                return result[0] > 0 if result else False

        except mysql.connector.Error as e:
            logger.error(f"Error checking for duplicate signal: {e}")
            return False
